/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <system_stm32f4xx.h>
#include <timer.h>
#include <ucglib.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static ucg_t ucg;
int main(void)
{
	SystemCoreClockUpdate();
	TimerInit();
	//Khoi tao LCD
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);

	ucg_SetFont(&ucg, ucg_font_baby_tf); //Lua chon font chu va co chu
	ucg_SetColor(&ucg, 0, 255, 0, 0); //Chon mau chu la mau trang
	ucg_SetColor(&ucg, 1, 0, 0, 0);//Mau Background la mau den
	ucg_SetRotate180(&ucg); //Xoay man hinh 180 do
	ucg_DrawString(&ucg, 72 , 128 , 0, "Nhom 6_TTCS"); //In dong chu ra LCD

	/* Loop forever */
	while(1){
		processTimerScheduler();
	}
}
